# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\x02ml\"8\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x14\n\x0cimage_format\x18\x02 \x01(\t\"&\n\x11\x45mbeddingResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x32\x44\n\tMLService\x12\x37\n\x0cGetEmbedding\x12\x10.ml.ImageRequest\x1a\x15.ml.EmbeddingResponseBAZ?github.com/noedaka/clothing-visual-search/backend/internal/mlpbb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/noedaka/clothing-visual-search/backend/internal/mlpb'
  _globals['_IMAGEREQUEST']._serialized_start=24
  _globals['_IMAGEREQUEST']._serialized_end=80
  _globals['_EMBEDDINGRESPONSE']._serialized_start=82
  _globals['_EMBEDDINGRESPONSE']._serialized_end=120
  _globals['_MLSERVICE']._serialized_start=122
  _globals['_MLSERVICE']._serialized_end=190
# @@protoc_insertion_point(module_scope)
