// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ml_service.proto

package mlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ImageData   []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData"`
	xxx_hidden_ImageFormat *string                `protobuf:"bytes,2,opt,name=image_format,json=imageFormat"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	mi := &file_ml_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ImageRequest) GetImageData() []byte {
	if x != nil {
		return x.xxx_hidden_ImageData
	}
	return nil
}

func (x *ImageRequest) GetImageFormat() string {
	if x != nil {
		if x.xxx_hidden_ImageFormat != nil {
			return *x.xxx_hidden_ImageFormat
		}
		return ""
	}
	return ""
}

func (x *ImageRequest) SetImageData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ImageData = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ImageRequest) SetImageFormat(v string) {
	x.xxx_hidden_ImageFormat = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ImageRequest) HasImageData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ImageRequest) HasImageFormat() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ImageRequest) ClearImageData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ImageData = nil
}

func (x *ImageRequest) ClearImageFormat() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ImageFormat = nil
}

type ImageRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	ImageData   []byte
	ImageFormat *string
}

func (b0 ImageRequest_builder) Build() *ImageRequest {
	m0 := &ImageRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ImageData != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_ImageData = b.ImageData
	}
	if b.ImageFormat != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_ImageFormat = b.ImageFormat
	}
	return m0
}

type EmbeddingResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Embedding []float32              `protobuf:"fixed32,1,rep,packed,name=embedding"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_ml_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EmbeddingResponse) GetEmbedding() []float32 {
	if x != nil {
		return x.xxx_hidden_Embedding
	}
	return nil
}

func (x *EmbeddingResponse) SetEmbedding(v []float32) {
	x.xxx_hidden_Embedding = v
}

type EmbeddingResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Embedding []float32
}

func (b0 EmbeddingResponse_builder) Build() *EmbeddingResponse {
	m0 := &EmbeddingResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Embedding = b.Embedding
	return m0
}

var File_ml_service_proto protoreflect.FileDescriptor

const file_ml_service_proto_rawDesc = "" +
	"\n" +
	"\x10ml_service.proto\x12\x02ml\"P\n" +
	"\fImageRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12!\n" +
	"\fimage_format\x18\x02 \x01(\tR\vimageFormat\"1\n" +
	"\x11EmbeddingResponse\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding2D\n" +
	"\tMLService\x127\n" +
	"\fGetEmbedding\x12\x10.ml.ImageRequest\x1a\x15.ml.EmbeddingResponseBAZ?github.com/noedaka/clothing-visual-search/backend/internal/mlpbb\beditionsp\xe8\a"

var file_ml_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ml_service_proto_goTypes = []any{
	(*ImageRequest)(nil),      // 0: ml.ImageRequest
	(*EmbeddingResponse)(nil), // 1: ml.EmbeddingResponse
}
var file_ml_service_proto_depIdxs = []int32{
	0, // 0: ml.MLService.GetEmbedding:input_type -> ml.ImageRequest
	1, // 1: ml.MLService.GetEmbedding:output_type -> ml.EmbeddingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_service_proto_init() }
func file_ml_service_proto_init() {
	if File_ml_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_service_proto_rawDesc), len(file_ml_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_service_proto_goTypes,
		DependencyIndexes: file_ml_service_proto_depIdxs,
		MessageInfos:      file_ml_service_proto_msgTypes,
	}.Build()
	File_ml_service_proto = out.File
	file_ml_service_proto_goTypes = nil
	file_ml_service_proto_depIdxs = nil
}
